<?php

namespace Database\Seeders;

use App\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    private array $badges = [

        // ════ SPECIAL ════════════════════════════════════════════════════════
        [
            'key'            => 'welcome',
            'name'           => 'Welcome to the Journey',
            'name_ar'        => 'مرحباً بك في الرحلة',
            'description'    => 'You created your account and began your Hifz journey on omarhesham.school.',
            'description_ar' => 'أنشأت حسابك وبدأت رحلة الحفظ على omarhesham.school.',
            'emoji'          => '🕌',
            'category'       => 'special',
            'tier'           => 'bronze',
            'xp_value'       => 25,
            'sort_order'     => 1,
        ],
        [
            'key'            => 'ramadan_warrior',
            'name'           => 'Ramadan Warrior',
            'name_ar'        => 'محارب رمضان',
            'description'    => 'Maintained a 3-day memorization streak during the blessed month of Ramadan.',
            'description_ar' => 'حافظت على سلسلة حفظ لمدة 3 أيام في شهر رمضان المبارك.',
            'emoji'          => '🌙',
            'category'       => 'special',
            'tier'           => 'gold',
            'xp_value'       => 200,
            'sort_order'     => 2,
        ],
        [
            'key'            => 'young_hafiz',
            'name'           => 'Young Hafiz',
            'name_ar'        => 'الحافظ الصغير',
            'description'    => 'As a young student, you logged 50 or more ayahs. MashaAllah!',
            'description_ar' => 'كطالب صغير، حفظت 50 آية أو أكثر. ما شاء الله!',
            'emoji'          => '⭐',
            'category'       => 'special',
            'tier'           => 'gold',
            'xp_value'       => 150,
            'sort_order'     => 3,
        ],
        [
            'key'            => 'faithful_year',
            'name'           => 'Faithful Year',
            'name_ar'        => 'سنة الوفاء',
            'description'    => 'You have been on the platform for a full year with 100+ sessions. True dedication!',
            'description_ar' => 'مررت عام كامل على المنصة مع 100+ جلسة. وفاء حقيقي!',
            'emoji'          => '🏛️',
            'category'       => 'special',
            'tier'           => 'platinum',
            'xp_value'       => 500,
            'sort_order'     => 4,
        ],

        // ════ STREAK ═════════════════════════════════════════════════════════
        [
            'key'            => 'first_log',
            'name'           => 'First Step',
            'name_ar'        => 'الخطوة الأولى',
            'description'    => 'You logged your very first Quran memorization session.',
            'description_ar' => 'سجّلت أول جلسة حفظ للقرآن الكريم.',
            'emoji'          => '🌱',
            'category'       => 'streak',
            'tier'           => 'bronze',
            'xp_value'       => 25,
            'sort_order'     => 10,
        ],
        [
            'key'            => 'streak_3',
            'name'           => '3-Day Streak',
            'name_ar'        => '3 أيام متتالية',
            'description'    => 'You memorized for 3 consecutive days. Keep the momentum!',
            'description_ar' => 'حفظت لمدة 3 أيام متتالية. واصل الزخم!',
            'emoji'          => '🔥',
            'category'       => 'streak',
            'tier'           => 'bronze',
            'xp_value'       => 50,
            'sort_order'     => 11,
        ],
        [
            'key'            => 'streak_7',
            'name'           => 'Week Warrior',
            'name_ar'        => 'محارب الأسبوع',
            'description'    => 'You memorized every day for a full week without missing a day.',
            'description_ar' => 'حفظت كل يوم طوال أسبوع كامل بدون انقطاع.',
            'emoji'          => '🔥',
            'category'       => 'streak',
            'tier'           => 'bronze',
            'xp_value'       => 100,
            'sort_order'     => 12,
        ],
        [
            'key'            => 'streak_14',
            'name'           => 'Fortnight of Faithfulness',
            'name_ar'        => 'أسبوعان من الالتزام',
            'description'    => 'Two full weeks of consecutive memorization sessions. Impressive!',
            'description_ar' => 'أسبوعان كاملان من جلسات الحفظ المتتالية. رائع!',
            'emoji'          => '🔥',
            'category'       => 'streak',
            'tier'           => 'silver',
            'xp_value'       => 150,
            'sort_order'     => 13,
        ],
        [
            'key'            => 'streak_30',
            'name'           => 'Month of Devotion',
            'name_ar'        => 'شهر التفاني',
            'description'    => 'A full month of memorization every single day. SubhanAllah!',
            'description_ar' => 'شهر كامل من الحفظ كل يوم. سبحان الله!',
            'emoji'          => '⚡',
            'category'       => 'streak',
            'tier'           => 'silver',
            'xp_value'       => 250,
            'sort_order'     => 14,
        ],
        [
            'key'            => 'streak_60',
            'name'           => 'Two Months Unbroken',
            'name_ar'        => 'شهران متواصلان',
            'description'    => 'Sixty consecutive days of Quran memorization. Truly remarkable!',
            'description_ar' => 'ستون يوماً متتالياً من حفظ القرآن. مذهل حقاً!',
            'emoji'          => '💫',
            'category'       => 'streak',
            'tier'           => 'gold',
            'xp_value'       => 400,
            'sort_order'     => 15,
        ],
        [
            'key'            => 'streak_100',
            'name'           => 'Century Streak',
            'name_ar'        => 'مئة يوم متتالية',
            'description'    => 'One hundred consecutive days of memorization. A legend in the making.',
            'description_ar' => 'مئة يوم متتالية من الحفظ. أسطورة في طور التكوين.',
            'emoji'          => '💯',
            'category'       => 'streak',
            'tier'           => 'platinum',
            'xp_value'       => 750,
            'sort_order'     => 16,
        ],
        [
            'key'            => 'longest_streak_7',
            'name'           => 'Best Week Ever',
            'name_ar'        => 'أفضل أسبوع على الإطلاق',
            'description'    => 'Your longest streak has reached 7 days — your personal best!',
            'description_ar' => 'وصلت أطول سلسلة لك إلى 7 أيام — أفضل رقم شخصي!',
            'emoji'          => '🏆',
            'category'       => 'streak',
            'tier'           => 'bronze',
            'xp_value'       => 75,
            'sort_order'     => 17,
        ],
        [
            'key'            => 'longest_streak_30',
            'name'           => 'Iron Will',
            'name_ar'        => 'إرادة من حديد',
            'description'    => 'Your personal best streak has reached 30 days.',
            'description_ar' => 'وصل أفضل رقم شخصي لك إلى 30 يوماً.',
            'emoji'          => '🛡️',
            'category'       => 'streak',
            'tier'           => 'silver',
            'xp_value'       => 200,
            'sort_order'     => 18,
        ],

        // ════ VOLUME ══════════════════════════════════════════════════════════
        [
            'key'            => 'ayahs_10',
            'name'           => 'First Ayahs',
            'name_ar'        => 'الآيات الأولى',
            'description'    => 'You have logged 10 ayahs of the Holy Quran.',
            'description_ar' => 'سجّلت 10 آيات من القرآن الكريم.',
            'emoji'          => '📖',
            'category'       => 'volume',
            'tier'           => 'bronze',
            'xp_value'       => 30,
            'sort_order'     => 20,
        ],
        [
            'key'            => 'ayahs_50',
            'name'           => 'Growing Memoriser',
            'name_ar'        => 'الحافظ النامي',
            'description'    => 'Fifty ayahs logged — you are building a solid foundation.',
            'description_ar' => 'خمسون آية مسجّلة — أنت تبني أساساً متيناً.',
            'emoji'          => '📖',
            'category'       => 'volume',
            'tier'           => 'bronze',
            'xp_value'       => 60,
            'sort_order'     => 21,
        ],
        [
            'key'            => 'ayahs_100',
            'name'           => 'Hundred Ayahs',
            'name_ar'        => 'مئة آية',
            'description'    => 'You have logged 100 ayahs in your Hifz journey. Alhamdulillah!',
            'description_ar' => 'سجّلت 100 آية في رحلة الحفظ. الحمد لله!',
            'emoji'          => '📚',
            'category'       => 'volume',
            'tier'           => 'silver',
            'xp_value'       => 100,
            'sort_order'     => 22,
        ],
        [
            'key'            => 'ayahs_500',
            'name'           => 'Half a Juz',
            'name_ar'        => 'نصف جزء',
            'description'    => '500 ayahs — equivalent to roughly half a juz. Keep going!',
            'description_ar' => '500 آية — ما يعادل تقريباً نصف جزء. واصل!',
            'emoji'          => '🌟',
            'category'       => 'volume',
            'tier'           => 'silver',
            'xp_value'       => 200,
            'sort_order'     => 23,
        ],
        [
            'key'            => 'ayahs_1000',
            'name'           => 'Thousand Ayahs',
            'name_ar'        => 'ألف آية',
            'description'    => 'One thousand ayahs logged. You have memorised roughly 4 juz worth of content!',
            'description_ar' => 'سجّلت ألف آية. حفظت ما يعادل نحو 4 أجزاء!',
            'emoji'          => '🌠',
            'category'       => 'volume',
            'tier'           => 'gold',
            'xp_value'       => 400,
            'sort_order'     => 24,
        ],
        [
            'key'            => 'ayahs_6236',
            'name'           => 'Complete Quran',
            'name_ar'        => 'القرآن الكريم كاملاً',
            'description'    => 'You have logged all 6,236 ayahs of the Holy Quran. Allahu Akbar!',
            'description_ar' => 'سجّلت جميع آيات القرآن الكريم البالغة 6236 آية. الله أكبر!',
            'emoji'          => '🕋',
            'category'       => 'volume',
            'tier'           => 'platinum',
            'xp_value'       => 2000,
            'sort_order'     => 25,
        ],
        [
            'key'            => 'sessions_10',
            'name'           => 'Ten Sessions',
            'name_ar'        => 'عشر جلسات',
            'description'    => 'You have completed 10 memorization sessions. Great start!',
            'description_ar' => 'أتممت 10 جلسات حفظ. بداية رائعة!',
            'emoji'          => '🎯',
            'category'       => 'volume',
            'tier'           => 'bronze',
            'xp_value'       => 40,
            'sort_order'     => 26,
        ],
        [
            'key'            => 'sessions_50',
            'name'           => 'Dedicated Student',
            'name_ar'        => 'الطالب المجتهد',
            'description'    => 'Fifty sessions completed — you are a dedicated student of the Quran.',
            'description_ar' => 'خمسون جلسة مكتملة — أنت طالب مجتهد في القرآن.',
            'emoji'          => '🎯',
            'category'       => 'volume',
            'tier'           => 'silver',
            'xp_value'       => 150,
            'sort_order'     => 27,
        ],
        [
            'key'            => 'sessions_100',
            'name'           => 'Century Club',
            'name_ar'        => 'نادي المئة',
            'description'    => 'One hundred memorization sessions completed. Outstanding commitment!',
            'description_ar' => 'مئة جلسة حفظ مكتملة. التزام استثنائي!',
            'emoji'          => '💎',
            'category'       => 'volume',
            'tier'           => 'gold',
            'xp_value'       => 300,
            'sort_order'     => 28,
        ],
        [
            'key'            => 'sessions_365',
            'name'           => 'Year of Sessions',
            'name_ar'        => 'عام من الجلسات',
            'description'    => '365 sessions — one for every day of the year. Legendary dedication.',
            'description_ar' => '365 جلسة — يوم لكل يوم في السنة. تفانٍ أسطوري.',
            'emoji'          => '👑',
            'category'       => 'volume',
            'tier'           => 'platinum',
            'xp_value'       => 1000,
            'sort_order'     => 29,
        ],
        [
            'key'            => 'surahs_3',
            'name'           => 'Multi-Surah',
            'name_ar'        => 'متعدد السور',
            'description'    => 'You have worked on 3 different surahs in your journey.',
            'description_ar' => 'عملت على 3 سور مختلفة في رحلتك.',
            'emoji'          => '📜',
            'category'       => 'volume',
            'tier'           => 'bronze',
            'xp_value'       => 40,
            'sort_order'     => 30,
        ],
        [
            'key'            => 'surahs_10',
            'name'           => 'Surah Explorer',
            'name_ar'        => 'مستكشف السور',
            'description'    => 'You have memorised from 10 different surahs of the Quran.',
            'description_ar' => 'حفظت من 10 سور مختلفة من القرآن الكريم.',
            'emoji'          => '🗺️',
            'category'       => 'volume',
            'tier'           => 'silver',
            'xp_value'       => 120,
            'sort_order'     => 31,
        ],
        [
            'key'            => 'surahs_30',
            'name'           => 'Juz Explorer',
            'name_ar'        => 'مستكشف الأجزاء',
            'description'    => 'You have worked on ayahs from 30 different surahs.',
            'description_ar' => 'عملت على آيات من 30 سورة مختلفة.',
            'emoji'          => '🧭',
            'category'       => 'volume',
            'tier'           => 'gold',
            'xp_value'       => 300,
            'sort_order'     => 32,
        ],
        [
            'key'            => 'surahs_114',
            'name'           => 'All 114 Surahs',
            'name_ar'        => 'جميع السور الـ114',
            'description'    => 'You have memorised ayahs from all 114 surahs of the Noble Quran.',
            'description_ar' => 'حفظت آيات من جميع سور القرآن الكريم البالغة 114 سورة.',
            'emoji'          => '🕋',
            'category'       => 'volume',
            'tier'           => 'platinum',
            'xp_value'       => 1500,
            'sort_order'     => 33,
        ],

        // ════ QUALITY ════════════════════════════════════════════════════════
        [
            'key'            => 'first_perfect',
            'name'           => 'First Perfect Session',
            'name_ar'        => 'أول جلسة مثالية',
            'description'    => 'You achieved a 5-star quality rating in a memorization session.',
            'description_ar' => 'حققت تقييم 5 نجوم في جلسة حفظ.',
            'emoji'          => '⭐',
            'category'       => 'quality',
            'tier'           => 'bronze',
            'xp_value'       => 50,
            'sort_order'     => 40,
        ],
        [
            'key'            => 'perfect_5',
            'name'           => 'Five Perfect Sessions',
            'name_ar'        => 'خمس جلسات مثالية',
            'description'    => 'Five 5-star sessions — your Tajweed and accuracy are excellent.',
            'description_ar' => 'خمس جلسات بـ5 نجوم — تجويدك ودقتك ممتازان.',
            'emoji'          => '🌟',
            'category'       => 'quality',
            'tier'           => 'silver',
            'xp_value'       => 100,
            'sort_order'     => 41,
        ],
        [
            'key'            => 'perfect_20',
            'name'           => 'Precision Memoriser',
            'name_ar'        => 'الحافظ الدقيق',
            'description'    => 'Twenty perfect sessions. Your recitation quality is outstanding.',
            'description_ar' => 'عشرون جلسة مثالية. جودة تلاوتك رائعة.',
            'emoji'          => '💫',
            'category'       => 'quality',
            'tier'           => 'gold',
            'xp_value'       => 250,
            'sort_order'     => 42,
        ],
        [
            'key'            => 'perfect_50',
            'name'           => 'Master Reciter',
            'name_ar'        => 'المتلو المتقن',
            'description'    => 'Fifty perfect sessions — a testament to your mastery of Tajweed.',
            'description_ar' => 'خمسون جلسة مثالية — شهادة على إتقانك للتجويد.',
            'emoji'          => '👑',
            'category'       => 'quality',
            'tier'           => 'platinum',
            'xp_value'       => 500,
            'sort_order'     => 43,
        ],
        [
            'key'            => 'high_quality_10',
            'name'           => 'Consistently Strong',
            'name_ar'        => 'قوة مستمرة',
            'description'    => 'Ten sessions rated 4 stars or above. You maintain high standards.',
            'description_ar' => 'عشر جلسات مُقيَّمة بـ4 نجوم أو أكثر. تحافظ على معايير عالية.',
            'emoji'          => '🎖️',
            'category'       => 'quality',
            'tier'           => 'bronze',
            'xp_value'       => 80,
            'sort_order'     => 44,
        ],
        [
            'key'            => 'avg_quality_4',
            'name'           => 'High Achiever',
            'name_ar'        => 'متفوق',
            'description'    => 'Your average session quality across 10+ sessions is 4.0 or higher.',
            'description_ar' => 'متوسط جودة جلساتك عبر 10+ جلسات هو 4.0 أو أعلى.',
            'emoji'          => '🏅',
            'category'       => 'quality',
            'tier'           => 'silver',
            'xp_value'       => 150,
            'sort_order'     => 45,
        ],
        [
            'key'            => 'avg_quality_45',
            'name'           => 'Excellence Standard',
            'name_ar'        => 'معيار التميّز',
            'description'    => 'Your average quality across 20+ sessions exceeds 4.5 stars. Exceptional!',
            'description_ar' => 'متوسط جودتك عبر 20+ جلسة يتجاوز 4.5 نجوم. استثنائي!',
            'emoji'          => '🌠',
            'category'       => 'quality',
            'tier'           => 'gold',
            'xp_value'       => 300,
            'sort_order'     => 46,
        ],

        // ════ CONSISTENCY ═════════════════════════════════════════════════════
        [
            'key'            => 'week_complete',
            'name'           => 'Perfect Week',
            'name_ar'        => 'أسبوع مثالي',
            'description'    => 'You logged at least one session every day for 7 days this week.',
            'description_ar' => 'سجّلت جلسة واحدة على الأقل كل يوم لمدة 7 أيام هذا الأسبوع.',
            'emoji'          => '✅',
            'category'       => 'consistency',
            'tier'           => 'silver',
            'xp_value'       => 100,
            'sort_order'     => 50,
        ],
        [
            'key'            => 'weekly_streak_4',
            'name'           => 'Monthly Consistency',
            'name_ar'        => 'ثبات شهري',
            'description'    => 'You have been active in 4 consecutive calendar weeks.',
            'description_ar' => 'كنت نشطاً لمدة 4 أسابيع تقويمية متتالية.',
            'emoji'          => '📅',
            'category'       => 'consistency',
            'tier'           => 'silver',
            'xp_value'       => 150,
            'sort_order'     => 51,
        ],
        [
            'key'            => 'weekly_streak_12',
            'name'           => 'Quarter Champion',
            'name_ar'        => 'بطل الربع',
            'description'    => 'Active every week for 3 consecutive months. Truly consistent!',
            'description_ar' => 'نشط كل أسبوع لمدة 3 أشهر متتالية. ثبات حقيقي!',
            'emoji'          => '🏆',
            'category'       => 'consistency',
            'tier'           => 'gold',
            'xp_value'       => 350,
            'sort_order'     => 52,
        ],
        [
            'key'            => 'double_session',
            'name'           => 'Double Session',
            'name_ar'        => 'جلسة مزدوجة',
            'description'    => 'You completed two or more memorization sessions in a single day.',
            'description_ar' => 'أتممت جلستين أو أكثر من الحفظ في يوم واحد.',
            'emoji'          => '⚡',
            'category'       => 'consistency',
            'tier'           => 'bronze',
            'xp_value'       => 60,
            'sort_order'     => 53,
        ],
        [
            'key'            => 'early_bird',
            'name'           => 'Early Bird',
            'name_ar'        => 'الطائر المبكر',
            'description'    => 'You logged a session before Fajr time — blessed early morning memorization!',
            'description_ar' => 'سجّلت جلسة قبل صلاة الفجر — حفظ صباحي مبارك!',
            'emoji'          => '🌅',
            'category'       => 'consistency',
            'tier'           => 'silver',
            'xp_value'       => 100,
            'sort_order'     => 54,
        ],
        [
            'key'            => 'night_owl',
            'name'           => 'Night Owl',
            'name_ar'        => 'بومة الليل',
            'description'    => 'You logged a session after 10pm — late-night Quran is still rewarded!',
            'description_ar' => 'سجّلت جلسة بعد الساعة 10 مساءً — حفظ الليل مكافأ أيضاً!',
            'emoji'          => '🌙',
            'category'       => 'consistency',
            'tier'           => 'bronze',
            'xp_value'       => 50,
            'sort_order'     => 55,
        ],
        [
            'key'            => 'unique_days_30',
            'name'           => 'Thirty Unique Days',
            'name_ar'        => 'ثلاثون يوماً فريداً',
            'description'    => 'You have logged sessions on 30 different calendar days.',
            'description_ar' => 'سجّلت جلسات في 30 يوماً تقويمياً مختلفاً.',
            'emoji'          => '📆',
            'category'       => 'consistency',
            'tier'           => 'silver',
            'xp_value'       => 120,
            'sort_order'     => 56,
        ],
        [
            'key'            => 'unique_days_100',
            'name'           => 'Hundred Days',
            'name_ar'        => 'مئة يوم',
            'description'    => 'You have memorized on 100 different days. A true commitment.',
            'description_ar' => 'حفظت في 100 يوم مختلف. التزام حقيقي.',
            'emoji'          => '💯',
            'category'       => 'consistency',
            'tier'           => 'gold',
            'xp_value'       => 300,
            'sort_order'     => 57,
        ],

        // ════ SOCIAL ══════════════════════════════════════════════════════════
        [
            'key'            => 'first_approval',
            'name'           => 'Teacher Approved',
            'name_ar'        => 'اعتماد المعلم',
            'description'    => 'Your teacher approved your first memorization session. Well done!',
            'description_ar' => 'اعتمد معلمك أول جلسة حفظ لك. أحسنت!',
            'emoji'          => '✅',
            'category'       => 'social',
            'tier'           => 'bronze',
            'xp_value'       => 50,
            'sort_order'     => 60,
        ],
        [
            'key'            => 'approved_10',
            'name'           => 'Trusted Student',
            'name_ar'        => 'الطالب الموثوق',
            'description'    => 'You have received 10 teacher approvals — your consistency is showing!',
            'description_ar' => 'حصلت على 10 اعتمادات من المعلم — ثباتك يظهر!',
            'emoji'          => '🤝',
            'category'       => 'social',
            'tier'           => 'silver',
            'xp_value'       => 120,
            'sort_order'     => 61,
        ],
        [
            'key'            => 'approved_50',
            'name'           => 'Star Pupil',
            'name_ar'        => 'النجم المميّز',
            'description'    => 'Fifty teacher approvals — you are an exemplary student of the Quran.',
            'description_ar' => 'خمسون اعتماداً من المعلم — أنت طالب قرآن مثالي.',
            'emoji'          => '🌟',
            'category'       => 'social',
            'tier'           => 'gold',
            'xp_value'       => 300,
            'sort_order'     => 62,
        ],
        [
            'key'            => 'has_teacher',
            'name'           => 'Guided Student',
            'name_ar'        => 'طالب مُوجَّه',
            'description'    => 'A teacher has been assigned to guide your Hifz journey.',
            'description_ar' => 'تم تعيين معلم لإرشاد رحلة حفظك.',
            'emoji'          => '👨‍🏫',
            'category'       => 'social',
            'tier'           => 'bronze',
            'xp_value'       => 40,
            'sort_order'     => 63,
        ],

        // ════ PROGRAM ═════════════════════════════════════════════════════════
        [
            'key'            => 'first_enroll',
            'name'           => 'Enrolled!',
            'name_ar'        => 'مُسجَّل!',
            'description'    => 'You enrolled in your first Hifz program on omarhesham.school.',
            'description_ar' => 'سجّلت في أول برنامج حفظ على omarhesham.school.',
            'emoji'          => '🎓',
            'category'       => 'program',
            'tier'           => 'bronze',
            'xp_value'       => 30,
            'sort_order'     => 70,
        ],
        [
            'key'            => 'multi_program',
            'name'           => 'Program Explorer',
            'name_ar'        => 'مستكشف البرامج',
            'description'    => 'You are enrolled in 3 or more programs simultaneously.',
            'description_ar' => 'أنت مسجّل في 3 برامج أو أكثر في آن واحد.',
            'emoji'          => '🗂️',
            'category'       => 'program',
            'tier'           => 'bronze',
            'xp_value'       => 60,
            'sort_order'     => 71,
        ],
    ];

    public function run(): void
    {
        foreach ($this->badges as $data) {
            Badge::updateOrCreate(
                ['key' => $data['key']],
                array_merge($data, [
                    'is_repeatable' => false,
                    'is_active'     => true,
                    'icon_color'    => match ($data['tier']) {
                        'bronze'   => '#CD7F32',
                        'silver'   => '#C0C0C0',
                        'gold'     => '#D4AF37',
                        'platinum' => '#E5E4E2',
                        default    => '#D4AF37',
                    },
                ])
            );
        }

        $this->command->info('  → BadgeSeeder: ' . count($this->badges) . ' badges created/updated.');
        $this->command->table(
            ['Category', 'Count'],
            collect($this->badges)
                ->groupBy('category')
                ->map(fn($g, $cat) => [$cat, $g->count()])
                ->values()
                ->toArray()
        );
    }
}
